### ISSUE TITLE
Vocabulary functions do not strip whitespace from CSV

### ISSUE THREAD

**Issue by admiralbumblebee** [knausj85/knausj_talon#321]
I had the misfortune the last few days to believe that the vocabulary csv files were not operating correctly.

Apparently whitespace is not stripped around fields. So "test, test2" leads a row which is parsed, but not turned into a functioning command.

**Comment by seabadger** [comment]
this might be the same as https://github.com/talonvoice/talon/issues/199, which was just fixed

**Comment by admiralbumblebee** [comment]
> this might be the same as [talonvoice/talon#199](https://github.com/talonvoice/talon/issues/199), which was just fixed

I replicated this behaviour using that Talon release, it's still an issue.

**Comment by rntz** [comment]
I have a fix for this, I just need to make a PR for it, I should get to it sometime tomorrow.
